import type { Metadata } from "next";
import { Outfit , Poppins, Inter } from "next/font/google";
import "./globals.css";
// import ClientLoaderWrapper from "@/component/ClientLoaderWrapper";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
});

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500'],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: "Sculpt-the-Maxillofacial-Clinic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} ${poppins.variable} ${inter.variable}antialiased`}
      >
        {/* <ClientLoaderWrapper> */}
          {children}
        {/* </ClientLoaderWrapper> */}
      </body>
    </html>
  );
}
